# Generated by Django 2.2.7 on 2019-11-19 18:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(max_length=16)),
                ('msg', models.TextField()),
                ('creationdate', models.DateTimeField(default=datetime.datetime(2019, 11, 19, 18, 24, 9, 399682, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Suscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
                ('creationdate', models.DateTimeField(default=datetime.datetime(2019, 11, 19, 18, 24, 9, 399990, tzinfo=utc))),
            ],
        ),
    ]
