# Generated by Django 2.2.7 on 2019-11-20 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='creationdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='suscriber',
            name='creationdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
